#!/usr/bin/env bash
DIR=$(dirname "${BASH_SOURCE[0]}")
CLANG=`which clang`
export LLVMCC="$CLANG -no-integrated-as -target armv7-gnu-linux-eabi"
"$DIR/cc1" "$@" > /dev/null
/usr/bin/arm-linux-gnueabi-g++ "$@"
