#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
ABS_DIR=$(cd "${DIR}"; pwd)

if [ "$1" = "make" ] || [ "$1" = "gmake" ] ; then
	"$@" CC="${ABS_DIR}/kint-gcc" CXX="${ABS_DIR}/kint-g++"
	exit
fi

CC="${ABS_DIR}/kint-gcc" CXX="${ABS_DIR}/kint-g++" "$@"
