#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
OPT="`llvm-config --bindir`/opt"
exec ${OPT} -disable-output -load=${DIR}/../lib/libintck.so \
	-targetlibinfo -tbaa -basicaa -globalopt -ipsccp -deadargelim \
	-simplifycfg -basiccg -prune-eh -inline -functionattrs -argpromotion \
	-scalarrepl-ssa -early-cse -simplify-libcalls -lazy-value-info \
	-jump-threading -correlated-propagation -simplifycfg \
	-strip-dead-prototypes -globaldce -constmerge \
	-overflow-idiom -adce -simplifycfg \
	-int-rewrite -overflow-simplify -int-libcalls \
	-std-compile-opts \
	-overflow-simplify -adce -simplifycfg \
	-load-rewrite \
	-O2 \
	-int-sat $@ 2>&1
