#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
OPT=`PATH=${DIR}:$PATH which opt`
${OPT} -disable-output -load=${DIR}/../lib/libintck.so \
	-targetlibinfo -tbaa -basicaa -globalopt -ipsccp -deadargelim \
	-simplifycfg -basiccg -prune-eh -inline -functionattrs -argpromotion \
	-scalarrepl-ssa -early-cse -simplify-libcalls -lazy-value-info \
	-jump-threading -correlated-propagation -simplifycfg \
	-strip-dead-prototypes -globaldce -constmerge \
	-overflow-idiom -adce -simplifycfg \
	-int-rewrite -overflow-simplify -int-libcalls \
	-std-compile-opts \
	-overflow-simplify -adce -simplifycfg \
	-load-elim \
	-O2 \
	-int-sat $@ 2>&1
