#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
OPT="`llvm-config --bindir`/opt"
exec ${OPT} --disable-output -load=${DIR}/../lib/libantiopt.so \
	-targetlibinfo -tbaa -basicaa -globalopt -deadargelim \
	-simplify-delete \
	-basiccg -prune-eh -inline-only -functionattrs -argpromotion \
	-strip-dead-prototypes \
	-simplify-libcalls -adce \
	-loop-rotate -ignore-loop-initial \
	-bugon-null -bugon-bounds \
	-bugon-int \
	-anti-simplify \
	-simplifycfg \
	-anti-dce \
	-simplifycfg \
	-show-bugon-true \
	"$@" 2>&1
