#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
OPT="`llvm-config --bindir`/opt"
exec ${OPT} --disable-output -load=${DIR}/../lib/libantiopt.so \
	-targetlibinfo -tbaa -basicaa -globalopt -ipsccp -deadargelim \
	-simplify-delete \
	-basiccg -prune-eh -inline-only -functionattrs -argpromotion \
	-scalarrepl-ssa -simplify-libcalls -adce \
	-bugon-undef \
	-bugon-null -bugon-gep -bugon-bounds \
	-bugon-alias \
	-bugon-int \
	-anti-simplify \
	-simplifycfg \
	-anti-dce \
	"$@" 2>&1
