#!/bin/bash

if [ "$1" = "-v" ]; then
  XARGSVERBOSE="-t"
  XARGSECHO=""
else
  XARGSVERBOSE=""
  XARGSECHO="echo Analyzing '{}' ;"
fi

DIR=$(dirname "${BASH_SOURCE[0]}")
NCPU=`${DIR}/ncpu`
OUT='pstack.txt'
TIMEOUT=5000
TOTALSEC=1000
find . -name '*.ll' -type f -print0 | xargs -0 -P ${NCPU} -I{} ${XARGSVERBOSE} bash -c "${XARGSECHO} ${DIR}/optck -smt-timeout=${TIMEOUT} -global-timeout-sec=${TOTALSEC} -enable-global-timeout '{}' > '{}.out'"
rm -f ${OUT}
find . -name '*.ll.out' -type f -print0 | xargs -0 -I{} bash -c "cat '{}' >> ${OUT}"

NBUGS=`grep -c ^bug: ${OUT}`
echo "Generated ${NBUGS} warnings, see ${OUT} for details."
