#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
NCPU=`${DIR}/ncpu`
OUT='poptck.txt'
TIMEOUT=5000
find . -name '*.ll' -type f -print0 | xargs -0 -P ${NCPU} -I{} -t bash -c "${DIR}/optck -smt-timeout=${TIMEOUT} '{}' > '{}.out'"
rm -f ${OUT}
find . -name '*.ll.out' -type f -print0 | xargs -0 -I{} bash -c "cat '{}' >> ${OUT}"
